# Generated by Django 5.0.2 on 2024-07-01 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('musics', models.ManyToManyField(to='hateyourmusic.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profile_icons/')),
                ('background', models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/')),
                ('following', models.IntegerField(blank=True, default=0)),
                ('followers', models.IntegerField(blank=True, default=0)),
                ('playlists', models.ManyToManyField(to='hateyourmusic.playlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='hateyourmusic.profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_of', to='hateyourmusic.profile')),
            ],
            options={
                'unique_together': {('followed', 'follower')},
            },
        ),
    ]
