# Generated by Django 5.0.2 on 2024-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Gen', 'Gênero'), ('Al', 'Álbum'), ('Ar', 'Artista'), ('Mus', 'Música')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
