# Generated by Django 5.0.2 on 2024-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0003_post_dt_alter_community_coms_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Gen', 'Gênero'), ('Al', 'Álbum'), ('Mus', 'Música'), ('Ar', 'Artista')], max_length=5),
        ),
    ]
