# Generated by Django 5.0.2 on 2024-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0005_remove_post_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Mus', 'Música'), ('Gen', 'Gênero'), ('Al', 'Álbum'), ('Ar', 'Artista')], max_length=5),
        ),
    ]
