# Generated by Django 5.0.2 on 2024-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0006_alter_community_coms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Mus', 'Música'), ('Al', 'Álbum'), ('Gen', 'Gênero'), ('Ar', 'Artista')], max_length=5),
        ),
    ]
