# Generated by Django 5.0.2 on 2024-06-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0006_alter_profile_profile_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_background',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
