# Generated by Django 5.0.2 on 2024-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0007_rename_profile_background_profile_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='background_default.png', upload_to='profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_default.jpg', upload_to='profile_pictures/'),
        ),
    ]
