# Generated by Django 5.0.2 on 2024-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0007_alter_community_coms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Al', 'Álbum'), ('Ar', 'Artista'), ('Gen', 'Gênero'), ('Mus', 'Música')], max_length=5),
        ),
    ]
