# Generated by Django 5.0.2 on 2024-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0008_alter_comment_author_alter_community_coms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Mus', 'Música'), ('Gen', 'Gênero'), ('Al', 'Álbum'), ('Ar', 'Artista')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='numOfComments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
