# Generated by Django 5.0.2 on 2024-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0008_alter_profile_background_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='background_default.png', upload_to='background_pictures/'),
        ),
    ]
