# Generated by Django 5.0.2 on 2024-06-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0009_alter_community_coms_alter_post_numofcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hateyourmusic.post'),
        ),
        migrations.AlterField(
            model_name='community',
            name='coms',
            field=models.CharField(choices=[('Ar', 'Artista'), ('Gen', 'Gênero'), ('Mus', 'Música'), ('Al', 'Álbum')], max_length=5),
        ),
    ]
