# Generated by Django 5.0.2 on 2024-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateyourmusic', '0009_alter_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='background_pictures/background_default.png', upload_to='background_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/profile_default.jpg', upload_to='profile_pictures/'),
        ),
    ]
